import { Link, useLocation, useParams } from "react-router-dom";
import { ArrowLeft, LayoutDashboard } from "lucide-react";
import type { AIResultView } from "../types/ai";
import { useTicket } from "../hooks/useTickets";
import { useDocumentTitle } from "../hooks/useDocumentTitle";
import { ticketToAIResult } from "../utils/ticketToAIResult";
import AIResultsPanel from "../components/tickets/AIResultsPanel";
import Button from "../components/ui/Button";
import PageHeader from "../components/ui/PageHeader";
import Spinner from "../components/ui/Spinner";
import EmptyState from "../components/ui/EmptyState";

export default function AIResultsPage() {
  const { id } = useParams<{ id: string }>();
  const location = useLocation();
  const stateResult = location.state?.result as AIResultView | undefined;
  const { ticket, loading, error } = useTicket(id, !stateResult);

  useDocumentTitle("AI Analysis");

  const fetchedResult = ticket ? ticketToAIResult(ticket) : null;
  const result = stateResult ?? fetchedResult;
  const ticketId = id ?? result?.ticketId;

  if (!stateResult && id && loading) {
    return <Spinner label="Loading analysis..." />;
  }

  if (error) {
    return (
      <div className="mx-auto max-w-2xl">
        <p className="rounded-lg bg-red-50 px-4 py-3 text-sm text-red-700">{error}</p>
      </div>
    );
  }

  if (!result) {
    return (
      <div className="mx-auto max-w-2xl">
        <EmptyState
          title="No analysis results"
          description={ticket && !ticket.category
            ? "This ticket has not been analyzed yet."
            : "Create a ticket or run analysis to see results."}
          action={
            <Link to={ticketId ? `/tickets/${ticketId}` : "/create"}>
              <Button>{ticketId ? "View Ticket" : "Create Ticket"}</Button>
            </Link>
          }
        />
      </div>
    );
  }

  return (
    <div className="mx-auto max-w-2xl space-y-6">
      <Link
        to={ticketId ? `/tickets/${ticketId}` : "/tickets"}
        className="inline-flex items-center gap-1.5 text-sm font-medium text-slate-500 hover:text-slate-700"
      >
        <ArrowLeft size={16} />
        {ticketId ? "View ticket" : "Back to tickets"}
      </Link>

      <PageHeader
        title="AI Analysis"
        description="Classification and summary generated by machine learning"
      />

      <AIResultsPanel result={result} />

      <div className="flex flex-wrap gap-3">
        {ticketId && (
          <Link to={`/tickets/${ticketId}`}>
            <Button variant="secondary">Ticket Details</Button>
          </Link>
        )}
        <Link to="/">
          <Button>
            <LayoutDashboard size={16} />
            Go to Dashboard
          </Button>
        </Link>
      </div>
    </div>
  );
}
